package com.ttqia.ez.sqlog.proxy;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;


import com.ttqia.ez.sqlog.po.JdbcMethod;
import com.ttqia.ez.sqlog.po.Monitor;
import com.ttqia.ez.sqlog.po.Params;
/**
 *
 * @author hepeng
 */
public class ProxyConnection implements Connection {
	Connection innerConnection;
	private Params param;

	public ProxyConnection(Connection connection, Params appId) {
		innerConnection = connection;
		this.param = appId;
	}

	public void fillMonitor(Monitor monitor, String method, String sql) {
		monitor.setAppId(param.getAppId());
		monitor.setConnName(innerConnection.toString());
		monitor.setJdbcMethod(method);
		monitor.setRow("" + (0));
		monitor.setSql(sql);
		SQLContext.monitor(monitor);
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {

		return new ProxyStatement(param,
				innerConnection.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability), this);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {

		return new ProxyPreparedStatement(param,
				innerConnection.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), this,
				sql);
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {

		return innerConnection.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {

		return new ProxyPreparedStatement(param, innerConnection.prepareStatement(sql, autoGeneratedKeys), this, sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {

		return new ProxyPreparedStatement(param, innerConnection.prepareStatement(sql, columnIndexes), this, sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {

		return new ProxyPreparedStatement(param, innerConnection.prepareStatement(sql, columnNames), this, sql);
	}

	@Override
	public Statement createStatement() throws SQLException {

		return new ProxyStatement(param, innerConnection.createStatement(), this);
	}

	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException {

		return new ProxyPreparedStatement(param, innerConnection.prepareStatement(sql), this, sql);
	}

	@Override
	public CallableStatement prepareCall(String sql) throws SQLException {

		return new ProxyCallableStatement(param, innerConnection.prepareCall(sql), this, sql);
	}

	@Override
	public String nativeSQL(String sql) throws SQLException {

		return innerConnection.nativeSQL(sql);
	}

	@Override
	public void setAutoCommit(boolean autoCommit) throws SQLException {

		innerConnection.setAutoCommit(autoCommit);
	}

	@Override
	public boolean getAutoCommit() throws SQLException {

		return innerConnection.getAutoCommit();
	}

	@Override
	public void commit() throws SQLException {

		Monitor monitor = new Monitor();
		try {
			innerConnection.commit();
		} finally {
			fillMonitor(monitor, JdbcMethod.COMMIT, JdbcMethod.COMMIT);
		}

	}

	@Override
	public void rollback() throws SQLException {

		Monitor monitor = new Monitor();
		try {
			innerConnection.rollback();
		} finally {
			fillMonitor(monitor, JdbcMethod.ROLLBACK, JdbcMethod.ROLLBACK );
		}
	}

	@Override
	public void rollback(Savepoint savepoint) throws SQLException {

		innerConnection.rollback();
	}

	@Override
	public void close() throws SQLException {
		innerConnection.close();
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {

		return new ProxyStatement(param, innerConnection.createStatement(resultSetType, resultSetConcurrency), this);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
			throws SQLException {

		return new ProxyPreparedStatement(param, innerConnection.prepareStatement(sql), this, sql);
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {

		return innerConnection.unwrap(iface);
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {

		return innerConnection.isWrapperFor(iface);
	}

	@Override
	public boolean isClosed() throws SQLException {

		return innerConnection.isClosed();
	}

	@Override
	public DatabaseMetaData getMetaData() throws SQLException {

		return innerConnection.getMetaData();
	}

	@Override
	public void setReadOnly(boolean readOnly) throws SQLException {

		innerConnection.setReadOnly(readOnly);
	}

	@Override
	public boolean isReadOnly() throws SQLException {

		return innerConnection.isReadOnly();
	}

	@Override
	public void setCatalog(String catalog) throws SQLException {

		innerConnection.setCatalog(catalog);
	}

	@Override
	public String getCatalog() throws SQLException {

		return innerConnection.getCatalog();
	}

	@Override
	public void setTransactionIsolation(int level) throws SQLException {

		innerConnection.setTransactionIsolation(level);
	}

	@Override
	public int getTransactionIsolation() throws SQLException {

		return innerConnection.getTransactionIsolation();
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {

		return innerConnection.getWarnings();
	}

	@Override
	public void clearWarnings() throws SQLException {

		innerConnection.clearWarnings();
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {

		return innerConnection.prepareCall(sql);
	}

	@Override
	public Map<String, Class<?>> getTypeMap() throws SQLException {

		return innerConnection.getTypeMap();
	}

	@Override
	public void setTypeMap(Map<String, Class<?>> map) throws SQLException {

		innerConnection.setTypeMap(map);
	}

	@Override
	public void setHoldability(int holdability) throws SQLException {

		innerConnection.setHoldability(holdability);
	}

	@Override
	public int getHoldability() throws SQLException {

		return innerConnection.getHoldability();
	}

	@Override
	public Savepoint setSavepoint() throws SQLException {

		return innerConnection.setSavepoint();
	}

	@Override
	public Savepoint setSavepoint(String name) throws SQLException {

		return innerConnection.setSavepoint(name);
	}

	@Override
	public void releaseSavepoint(Savepoint savepoint) throws SQLException {

		innerConnection.releaseSavepoint(savepoint);
	}

	@Override
	public Clob createClob() throws SQLException {

		return innerConnection.createClob();
	}

	@Override
	public Blob createBlob() throws SQLException {

		return innerConnection.createBlob();
	}

	@Override
	public NClob createNClob() throws SQLException {

		return innerConnection.createNClob();
	}

	@Override
	public SQLXML createSQLXML() throws SQLException {

		return innerConnection.createSQLXML();
	}

	@Override
	public boolean isValid(int timeout) throws SQLException {

		return innerConnection.isValid(timeout);
	}

	@Override
	public void setClientInfo(String name, String value) throws SQLClientInfoException {
		innerConnection.setClientInfo(name, value);
	}

	@Override
	public void setClientInfo(Properties properties) throws SQLClientInfoException {
		innerConnection.setClientInfo(properties);
	}

	@Override
	public String getClientInfo(String name) throws SQLException {
		return innerConnection.getClientInfo(name);
	}

	@Override
	public Properties getClientInfo() throws SQLException {
		return innerConnection.getClientInfo();
	}

	@Override
	public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
		return innerConnection.createArrayOf(typeName, elements);
	}

	@Override
	public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
		return innerConnection.createStruct(typeName, attributes);
	}

	@Override
	public void setSchema(String schema) throws SQLException {
		innerConnection.setSchema(schema);
	}

	@Override
	public String getSchema() throws SQLException {
		return innerConnection.getSchema();
	}

	public void abort(Executor executor) throws SQLException {
		innerConnection.abort(executor);
	}

	public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
		innerConnection.setNetworkTimeout(executor, milliseconds);
	}

	public int getNetworkTimeout() throws SQLException {
		return innerConnection.getNetworkTimeout();
	}

	@Override
	public String toString() {
		return (new StringBuilder(param.getAppId() + "@")).append(Integer.toHexString(innerConnection.hashCode()))
				.toString();
	}

	public Params getParam() {
		return param;
	}

	public void setParam(Params param) {
		this.param = param;
	}

}
